### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ghost** [gabru-md/LinuxSpells#5]
There are some changes to the readme file that could be made:

- [x] Replacing [this](https://github.com/gabru-md/LinuxSpells/blob/master/spells/images/spellsJS.png?raw=true) image with an up to date image containing `accio`
- [x] Format the lists properly

**Comment by luvhalvorson** [comment]
Hi, may you assign this to me? And I wonder what `accio` is?

**Comment by luvhalvorson** [comment]
I'm done! See #8 :) Thanks!

**Comment by gabru-md** [comment]
`accio` works instead of `wget` in linux.
Thanks for your contribution.
